### ISSUE TITLE
Proposal 

### ISSUE THREAD

**Issue by faierbol** [manjurulhoque/QuickAd-Django-Classified-App#2]
Hi man,
i really like this app, i have a project opened on freelancer.com to build a social commerce site
if you want you can bid on my project and we can work on it.
Please specify in your bid that we discussed on github
https://www.freelancer.com/projects/php/Build-marketplace-classifieds-website/details

**Comment by manjurulhoque** [comment]
Hi @faierbol 

I don't have account on freelancer. I am available on upwork. If you are comfortable with upwork, then let me know.

**Comment by faierbol** [comment]
This is my project details:

I would like someone to build me a marketplace/ classifieds website.
I will need this site built In Django framework using any open source application available on GitHub or in Laravel using this open source app https://marketplacekit.com/
Basically, i need a marketplace/ classifieds builder so i can customize it to my needs.
The site needs have a clean design like Airbnb, Facebook marketplace and letgo.com. and will also have the following features besides the features that already exists on https://marketplacekit.com/

**Comment by faierbol** [comment]
[Site requirements (1).docx](https://github.com/manjurulhoque/QuickAd-Django-Classified-App/files/4824823/Site.requirements.1.docx)

**Comment by faierbol** [comment]
pls take a look on site requirements and let me know if we can work on this on upwork.com

**Comment by faierbol** [comment]
[Archive.zip](https://github.com/manjurulhoque/QuickAd-Django-Classified-App/files/4824830/Archive.zip)

**Comment by faierbol** [comment]
this is a barebones mockup of the site

**Comment by faierbol** [comment]
My domain is ielo.ro

**Comment by manjurulhoque** [comment]
Sure, let me check and get back to you soon.

**Comment by faierbol** [comment]
thx

**Comment by manjurulhoque** [comment]
@faierbol I am able to handle this project. Could you tell me your budget and time?

**Comment by faierbol** [comment]
450-500 e

**Comment by faierbol** [comment]
1 month

**Comment by manjurulhoque** [comment]
Actually you have lot's of features so 500 won't cover it.

**Comment by faierbol** [comment]
Ok thx
